from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "data_table" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "ID_UCH_VOST_POL" INT NOT NULL,
    "NAME_BEGIN_VOST_UCH" VARCHAR(25) NOT NULL,
    "ESR_BEGIN_VOST_UCH" INT NOT NULL,
    "DOR_BEGIN_VOST_UCH" INT NOT NULL,
    "OKATO_BEGIN_VOST_UCH_NAME" VARCHAR(100) NOT NULL,
    "X_BEG_VOST_UCH" DOUBLE PRECISION NOT NULL,
    "Y_BEG_VOST_UCH" DOUBLE PRECISION NOT NULL,
    "NAME_END_VOST_UCH" VARCHAR(25) NOT NULL,
    "ESR_END_VOST_UCH" INT NOT NULL,
    "DOR_END_VOST_UCH" INT NOT NULL,
    "OKATO_END_VOST_UCH_NAME" VARCHAR(100) NOT NULL,
    "X_END_VOST_UCH" DOUBLE PRECISION NOT NULL,
    "Y_END_VOST_UCH" DOUBLE PRECISION NOT NULL,
    "NUM_CNSI_MELK_SET" INT NOT NULL,
    "NAME_BEGIN_MELK_SET" VARCHAR(29) NOT NULL,
    "ESR_BEGIN_MELK_SET" INT NOT NULL,
    "DOR_BEGIN_MELK_SET" INT NOT NULL,
    "OKATO_BEGIN_MELK_SET_NAME" VARCHAR(100) NOT NULL,
    "NAME_END_MELK_SET" VARCHAR(29) NOT NULL,
    "ESR_END_MELK_SET" INT NOT NULL,
    "DOR_END_MELK_SET" INT NOT NULL,
    "OKATO_END_MELK_SET_NAME" VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSONB NOT NULL
);"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
